import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import { IoIosLogOut } from 'react-icons/io'
import { useEffect, useState } from 'react'
import { signIn, signOut, useSession } from 'next-auth/react'
import axios from 'axios'
import Shortened from '@/components/Shortened'
import useSWR from 'swr'
import { toast, ToastContainer } from 'react-toastify'

export default function Home() {
  const [value, setValue] = useState("");
  const [errors, setErrors] = useState()
  const { data: session } = useSession();

  const fetcher = (url) => axios.get(url).then((res) => res.data);

  const { data: urls, error, isLoading, mutate } = useSWR(
    session ? `https://rexdirect.vercel.app/details?email=${session.user?.email}` : null,
    fetcher
  );

  const handleSubmit = async () => {
    if (session) {
      await axios.post("https://rexdirect.vercel.app/new", {
        email: session.user?.email,
        originalUrl: value,
      }).then(() => {
        mutate()
        setErrors()
        setValue("");
      }).catch(error => setErrors(error.message));

    }
  };

  const handleDelete = async (url) => {
    const notify = () => toast.error('Deleted !', {
      position: "bottom-right",
      autoClose: 2000,
      hideProgressBar: true,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "colored",
    });
    if (session) {
      await axios.delete(`https://rexdirect.vercel.app/delete/${url._id}`).then(notify());
      mutate((urls) => {
        return urls.filter((e) => e._id !== url._id);
      }, true);
    }
  };
  const handleSignInWithGoogle = () => {
    signIn("google");
  };

  return (
    <>
      <Head>
        <title>Rex App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center pt-[5rem]  ">
        <div className=" text-3xl lg:text-5xl my-7 ">URL SHORTENER✺</div>
        {session ?
          <div className="w-10/12 flex gap-2  items-center  lg:w-5/12 justify-between my-4">
            <div className='flex gap-3'>

              <img className='rounded-full h-12 border-black/30 border-4' src={session.user.image} />
              <div className="text-2xl my-auto flex">Hi, {session.user?.name.split(' ')[0]}</div>
            </div>
            <IoIosLogOut onClick={() => signOut()} className='bg-black/20 text-white cursor-pointer hover:scale-105 lg:w-10 w-12 h-12  lg:h-10 p-3 rounded-full' />
          </div>
          :
          <div>

            <button className=" bg-black/20 rounded-full hover:scale-95 duration-300   hover:text-white hover:bg-black/80  p-3 h-full " onClick={handleSignInWithGoogle} >Login to continue</button>

          </div>
        }
        {
          errors ? <div className='bg-red-500/20 text-red-500 border-4 border-red-500 px-5 py-2 my-4 rounded-xl'>{errors}</div> : ''
        }
        {
          session &&

          <form onSubmit={(e) => {
            e.preventDefault()
            handleSubmit()

          }} className="   w-10/12 flex gap-2  h-[50px]  lg:w-5/12 ">

            <input value={value} onChange={(e) => setValue(e.target.value)} placeholder="Paste the URL to shorten" className=" bg-white/40 border-2 border-black/20 placeholder:text-black/70 flex-1  px-4 backdrop-blur-md rounded-3xl  outline-none" />
            <button
            >

              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className=" bg-black/20 rounded-full hover:scale-95 duration-300  hover:rotate-180 hover:text-white hover:bg-black/80  p-3 h-full ">
                <path strokeLinecap="round" strokeLinejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" />
              </svg>
            </button>


          </form>}
        {session &&

          <div className=" w-10/12 flex  flex-col gap-2 my-4 lg:w-5/12">
            {urls && !isLoading ?
              urls.map((e) => <Shortened key={e._id} url={e} handleDelete={handleDelete} />)
              : <div className='w-10/12 my-2 mx-auto'>Loading</div>
            } </div>
        }
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
      </main>
    </>
  );
};
